[book]
authors = ["Phodal Huang"]
language = "en"
multilingual = false
src = "src"
title = "AI 辅助软件 IDE 插件与 AI 智能体示例"

[output.html]
git-repository-url = "https://github.com/phodal/ai4se"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/phodal/ai4se/edit/master/{path}"
site-url = "/"
cname = "ai4se.phodal.com"
